### ISSUE TITLE
Select which techs/sciences/missions/buildings to unlock

### ISSUE THREAD

**Issue by hickeys** [oliversalzburg/cbc-kitten-scientists#105]
Same as policies

**Comment by oliversalzburg** [comment]
Yeah, most definitely 👍

**Comment by oliversalzburg** [comment]
- [X] Policies
- [X] Techs
- [X] Upgrades
- [ ] Missions
- [ ] Building Upgrades

**Comment by oliversalzburg** [comment]
This should be complete now. Let me know if something doesn't work for you.
