### ISSUE TITLE
Per-building trigger value

### ISSUE THREAD

**Issue by hickeys** [oliversalzburg/cbc-kitten-scientists#106]
For example, I want to build workshops and factories ASAP, but I don't want to build another accelerator unless I'm capped on titanium

**Comment by oliversalzburg** [comment]
Controlling with this level of granularity is outside of the scope of this script. The challenges that would have to be solved to enable this far outweigh potential benefits. This already starts with the fact that you can't get a proper overview of all your configured trigger values. The potential to end up in highly confusing configuration situation is very high. We'd also have to store a new trigger value for every single building in our state, even though I would consider it highly unlikely that users would want to mess with the majority of these values.

As new features aren't approached currently anyway, this is highly unrealistic to ever be integrated at all. Sorry.
