### ISSUE TITLE
Crafting Expand/collapse button inverted state

### ISSUE THREAD

**Issue by hickeys** [oliversalzburg/cbc-kitten-scientists#110]
Somehow (I suspect by alternating between the resource and crafting lists) the state of the expand/collapse button got out of sync with the state of the UI.

<img width="458" alt="Screen Shot 2022-07-02 at 11 53 58 PM" src="https://user-images.githubusercontent.com/8008261/177028727-4e9be0dc-ab60-46e6-add6-49ec541e1475.png">
<img width="462" alt="Screen Shot 2022-07-02 at 11 53 48 PM" src="https://user-images.githubusercontent.com/8008261/177028728-20541412-f167-4eca-92f7-8c23aee00cbc.png">

**Comment by oliversalzburg** [comment]
This should have been fixed in 19a97331c43be4bf336f30bded241cc5df6c94c5

**Comment by hickeys** [comment]
Happy to test this if you want. Is there a pre-release url I can use?

**Comment by oliversalzburg** [comment]
The "Development Build" at https://github.com/oliversalzburg/cbc-kitten-scientists/releases has always the absolute latest changes in it.

**Comment by hickeys** [comment]
Looks fixed to me. Thank you!
