### ISSUE TITLE
Add option to automatically swap leaders for bonuses

### ISSUE THREAD

**Issue by Jian-Wuyou** [oliversalzburg/cbc-kitten-scientists#111]
That is, if the player manually assigned a specific kitten as leader (named Leader A), and you need, for example, a Chemist to improve the autocrafted Eludium, then the script will swap to a Chemist kitten before crafting the Eludium, after which it swaps back to the original kitten.

**Comment by oliversalzburg** [comment]
New features will not be added for the foreseeable future and this doesn't sound like something that would be implemented anytime soon thereafter. Micro-managing leader assignment for additional boosts sounds like it would introduce a lot of complexity for relatively little gain. As I don't want to collect open issues that will never be worked on, I'm closing this.
