### ISSUE TITLE
Feature-request: Add color-coding for workshop stock

### ISSUE THREAD

**Issue by adamaxis** [oliversalzburg/cbc-kitten-scientists#121]
This is more a feature request than an issue, but it would be really neat if there were color coding for workshop stock. Currently, the text is all black.

E.G:
1) You set a stock for 1T slabs,
2) It checks to see how many slabs are available
3) Text for 'slab' becomes red if you have <1T, green if >=1T

I use the workshop stock tab to set goals prior to a reset, so it's useful to see what is lacking/sufficient.

**Comment by oliversalzburg** [comment]
That is reasonable, as support for this existed in v1.5. I'll try to bring it back.

**Comment by oliversalzburg** [comment]
Let me know if this works for you. I might mess with the specific UI adjustments still though. Maybe something a bit more subtle could work, like the "stock capped" indicators already in the game.
