### ISSUE TITLE
Request: Remember time crystal maximum amount setting

### ISSUE THREAD

**Issue by adamaxis** [oliversalzburg/cbc-kitten-scientists#122]
So in-game, the maximum skip setting under time control->time skip resets to 50 every time the browser is closed.

I tend to adjust this setting as I play to get to near 100% unobtainium per skip. idk if it was an oversight or intentional, but could you add an option maybe to remember what the user sets it to?

Thank you

**Comment by oliversalzburg** [comment]
That actually sounds like a bug. I'm currently rewriting the entire settings system. Maybe it'll already be fixed in the process of it.

**Comment by oliversalzburg** [comment]
Interestingly, it seems like there never was an option for this in the storage system of the original script. I added that yesterday and this setting should now persist as you expect.

**Comment by oliversalzburg** [comment]
Correction. I only half-fixed it 😅
