### ISSUE TITLE
Bug: Some auto crafting not working initially

### ISSUE THREAD

**Issue by Fhurries** [oliversalzburg/cbc-kitten-scientists#124]
Some crafting is not working as intended - if you have zero of certain crafted items (IE, want to craft alloy and have zero alloy) then alloy will not be crafted. After manually crafting, automation functions as expected.

Possibly affects all crafting but due to trading you receive some crafted items and thus automation begins. Have not purposely tested this scenario but is assumed based on natural progression. Otherwise, with complete automation from reset and no manual interaction you will never craft the following and thus progress halts:
Gear, Alloy, Scaffold, Trade Ship, Tanker, Megalith

Side note: Using tampermonkey is there a way to completely wipe cached settings? Perhaps this is an issue between version? This has only started since removing alpha3, deleting permanently from TM, and installing alpha4.

**Comment by oliversalzburg** [comment]
Thanks for the detailed report. I have also noticed that there's something up. I feel like I recently broke something that causes this issue. I will investigate it after my next reset.

There is currently no great way to reset the settings, but you can inspect the Local Storage with your browser's DevTools and delete the `cbc.kitten-scientists` key. The script should then load default settings on the next page reload. But I doubt this will have an impact on the issue. This will most likely require code changes.

**Comment by Fhurries** [comment]
I will leave everything as is for now. If you end up needing an update on the nightly or dev release for this issue let me know here and I'll confirm on my end if they work as well.
