### ISSUE TITLE
Max limit on Unicorn Pastures Ignored

### ISSUE THREAD

**Issue by Fhurries** [oliversalzburg/cbc-kitten-scientists#126]
As stated, the max field for this building is ignored and it will continue to build past what you've entered.
Piggybacking - does this impact the auto build "best" unicorn building or is that feature totally disabled at the moment?

**Comment by oliversalzburg** [comment]
I feel like this might be another bug that only slipped into the latest alpha. I have not noticed this in my own game on the latest development snapshot. I'll verify this before the next release.

It does not impact the "best unicorn building" feature, which is entirely disabled internally right now. It will be resurrected though.

**Comment by oliversalzburg** [comment]
This should be fixed in the next build. Those unicorn pastures always need special handling 🙄
