### ISSUE TITLE
Bonfire auto build is not working.

### ISSUE THREAD

**Issue by larat3** [oliversalzburg/cbc-kitten-scientists#54]
Tried all the triggers for some reason it wouldn't auto buy anything. Other than that everything else seems to work.

**Comment by larat3** [comment]
I did a re install of the old kitten scientist and it seemed to fix it. Didnt try it on this one with the overhaul but should also work since before i just added it on top of it and didnt install it fresh.

**Comment by oliversalzburg** [comment]
If both scripts are active at the same time, that could be a problem. Not sure what exactly went wrong here. Thanks for trying both versions anyway :)
