### ISSUE TITLE
Script not working for buildings

### ISSUE THREAD

**Issue by Nic0zzz** [oliversalzburg/cbc-kitten-scientists#55]
I've been wanting to use this version of the script since the original one breaks the layout so badly however no buildings are being built even when it is the only option selected. Same settings as the original one but this version does not manage to make buildings whereas the other one does.

**Comment by oliversalzburg** [comment]
There was a bug in the BulkManager, which I just fixed. You may want to try again.

However, note that I never completed porting all the latest upstream changes. So some things might still not work as expected.

**Comment by Nic0zzz** [comment]
Thank you so much!
And yes I did notice that some things like autopraising, eludium crafting and the filters not working but I usually do this on my own so it's not a problem.
Thanks again.
