### ISSUE TITLE
Order of the Sun not being researched

### ISSUE THREAD

**Issue by TimJones** [oliversalzburg/cbc-kitten-scientists#95]
I have enabled Auto Religion, with a trigger value of `0`, and all "Order of the Sun" upgrades enabled but KSv2 doesn't seem to actually do the religion research.

Edit: forgot to mention that this is using [latest nightly](https://github.com/oliversalzburg/cbc-kitten-scientists/commit/754e9602364d8aee8b00ff61aec711418c20a3f6).

![image](https://user-images.githubusercontent.com/113170/170968254-21b54f01-2252-4d8a-b10e-ee2c31ba805b.png)

**Comment by oliversalzburg** [comment]
Could you provide your KG save export for this scenario? I currently don't have a good game state to test this.

**Comment by TimJones** [comment]
It's not the same state, but I exported into this gist with resources for Golden Spire & Sun Altar and neither being auto-researched.

https://gist.github.com/TimJones/dc09e276cbd4cc2ff0c502093d70f1bb

**Comment by oliversalzburg** [comment]
Thanks. This is really absolutely broken. Probably due to "Build best unicorn building first" change that was introduced fairly recently into v1. Working on a fix

**Comment by oliversalzburg** [comment]
There were multiple smaller issues here that should now all be resolved and the Order of the Sun upgrades should be purchased as expected.

There should be a development build of the userscript available any moment.

I disabled the "Build best unicorn building first" feature for now. I will have to evaluate that with another game state before I can enable it again.

**Comment by TimJones** [comment]
Thanks for the fix, shame about the build-best option having to be disabled for now.
Let me know if I can provide more game states or anything to help out more.

Cheers!
